config/routes.rb
Rails.application.routes.draw do
  resources :messages

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "new_photo" => "users#edit", :as => "new_photo"
  root :to => "users#new"
  resources :users
  resources :sessions
end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user  
  attr_accessible :content, :lat, :long, :user_id
  validates :user_id,  :presence => true
  validates :content, :presence => true
  validates :lat, :presence => true
  validates :long, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :image
  
  cattr_accessor :current_user 

  mount_uploader :image, ImageUploader
  has_many :messages, dependent: :destroy
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  
  
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	helper_method :current_user
	helper_method :message

	before_filter :set_current_user
	def set_current_user
		User.current_user = current_user
	end
	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def message
		@message = Message.all
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to new_message_path }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user_id, :content, :lat, :long)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	  user = User.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to new_message_path, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to log_in_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
require 'rails/all'
require 'carrierwave'
class UsersController < ApplicationController
	def new
		redirect_to new_message_path if current_user
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    redirect_to log_in_url, :notice => "Signed up!"
	  else
	    render "new"
	  end
	end

	def edit
		@user = User.find_by_id(params[:id])
	end

	def update
		@user = User.find_by_id(params[:id])

		if @user.update_attributes(params[:user])
			redirect_to new_message_path, :notice => "Photo Updated"
		else
			render "edit"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>MapChat</title>

    <style type="text/css">
      #map-canvas { height: 100%; width: 100%; margin: 0; padding: 0;}
    </style>
    <script type="text/javasript" src= "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD7Qw6vLHAA8ci7HuvffwlzwrtY92KC6cA">
    </script>
    <script type="text/javascript">
      google.maps.event.addDomListener(window, 'load', initialize);
      function initialize() {
        navigator.geolocation.getCurrentPosition(showPosition);
        function showPosition (position) {
          var mapOptions = {
            center: { lat: position.coords.latitude, lng: position.coords.longitude},
            zoom: 14
          };
          var map = new google.maps.Map(document.getElementById('map-canvas'),
              mapOptions);
          var markers=[];
          var windows=[];
          <%i=0%>
          <% message.each do |m| %>

            markers[<%=i%>] = new google.maps.Marker({
            position: {lat:<%=m.lat%>, lng:<%=m.long%>},
            map: map,
            title: <%= raw("\"" + m.user.email + "\"")%>,
            });

            windows[<%=i%>] = new google.maps.InfoWindow({
            content: "<div style = \" display:inline-block; vertical-align:top;\"> <img src = \"" + <%= raw("\"" + m.user.image.to_s + "\"")%> + "\"/>" +"</div> <div style = \" display:inline-block;\" > <p style = \"width: 200px;\">" +
            <%=raw("\"" + m.content + "\"")%>+"</p></div>"
            });

            google.maps.event.addListener(markers[<%=i%>], 'click', function() {
            windows[<%=i%>].open(map,markers[<%=i%>]);
            });

            <% i+=1 %>

          <%end%>

        }
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <% if current_user %>
            <h1><%= link_to "MapChat", new_message_path %></h1>
          <% else %>
            <h1><a href="#">MapChat</a></h1>
          <% end %>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <% if current_user %>
            <li><a><%= current_user.email %></a></li>
            <li><%= link_to "Edit Photo", new_photo_path(current_user) %></li>
            <li><%= link_to "Log out", log_out_path %></li>
          <% else %>
            <li><%= link_to "Sign up", sign_up_path %></li>
            <li><%= link_to "Log In", log_in_path %></li>
          <% end %>
        </ul>
      </section>
    </nav>

    <%= yield %>

    <div id="map-canvas"></div>

  </body>
</html>

app/views/messages/_form.html.erb
<div class="panel" id="postMessageForm">
<div class = "row">
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p class="hide" id="userIdShow"><%= current_user.id %></p>
  <div class="field hide">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, id:"userIdField" %>
  </div>
  <div class="field small-10 columns no-pad-right">
    <%= f.text_field :content, placeholder:"Type Message Here..." %>
  </div>
  <div class="field hide">
    <%= f.label :lat %><br>
    <%= f.text_field :lat, id:"latField"%>
  </div>
  <div class="field hide">
    <%= f.label :long %><br>
    <%= f.text_field :long, id:"longField" %>
  </div>
  <div class="actions small-2 columns no-pad-left">
    <div class="hide"><%= f.submit "Send", id:"sendMessageButton" %></div>
    <a href="#" class="button postfix" id="sendMessage">Send</a>
  </div>
  <script>
    function clickSubmit(){
      document.getElementById('sendMessageButton').click();
    }
    var sendMessageAnchor = document.getElementById('sendMessage');
    sendMessage.addEventListener("click", clickSubmit);
    navigator.geolocation;
    navigator.geolocation.getCurrentPosition(function(position){
      var lat = position.coords.latitude;
      var long = position.coords.longitude;
      document.getElementById('latField').value = lat;
      document.getElementById('longField').value = long;
    });
    var user = document.getElementById('userIdShow').innerHTML;
    console.log(user);
    document.getElementById('userIdField').value = user;
  </script>
<% end %>
</div>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Lat</th>
      <th>Long</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.user_id %></td>
        <td><%= message.content %></td>
        <td><%= message.lat %></td>
        <td><%= message.long %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<%= render 'form' %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @message.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @message.long %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/edit.html.erb
<div class = "panel" id="editPhotoPanel">
<h1> Add Picture </h1>
<%= form_for current_user do |f| %>
	<p>

		<%= f.file_field :image %>

		<div class="hide"><%= f.submit "Update Photo", id:"updatePhotoButton" %></div>
		<a href="#" class="button round" id="updatePhoto">Send</a>
	</p>

<% end %>
<script>
function clickSubmit(){
	document.getElementById('updatePhotoButton').click();
}
updatePhoto.addEventListener('click',clickSubmit);
</script>

</script>
</div>

app/views/users/new.html.erb
<div class="panel" id="signUpPanel">
<%= form_for @user do |f| %>
  <h1>Sign Up</h1>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "row">
    <div class="small-12 small-centered columns">
      <input id="user_email" name="user[email]" type="text" placeholder="Email">
    </div>
  </div>
  <div class="row">
    <div class="small-6 columns">
      <input id="user_password" name="user[password]" type="password" placeholder="Password">
    </div>
    <div class="small-6 columns">
      <input id="user_password_confirmation" name="user[password_confirmation]" type="password" placeholder="Password Confirmation">
    </div>
  </div>
  
  
  <div class="row">
    <div class="small-12 small-centered columns">
      <input class="button expand" name="commit" type="submit" value= "Sign Up" >
    </div>
  </div>
<% end %>
</div>